In [422]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [423]:
df_train = pd.read_csv('logical-rythm-2k20-game-price-prediction/steam_train.csv')
df_test = pd.read_csv('logical-rythm-2k20-game-price-prediction/steam_test.csv')

In [424]:
df_train.head(5)

appid                                             name release_date  \
0  708830                             The Armament Project   2017-09-28   
1  538000  Hop Step Sing! Kisekiteki Shining! (HQ Edition)   2017-06-29   
2  603530                             A Robot Named Fight!   2017-09-07   
3  564040                                     ZANGEKI WARP   2017-02-15   
4  951940                     Almost There: The Platformer   2019-02-19   

   english                              developer  \
0        1                                 DysTop   
1        1  Kodansha;Polygon Pictures Inc.;Lantis   
2        1                      Matt Bitner Games   
3        1                             ASTRO PORT   
4        1                            Bony Yousuf   

                           publisher          platforms  required_age  \
0                             DysTop            windows             0   
1                             Degica            windows             0   
2                  Matt Bitner Games  windows;mac;linux             0   
3                          Nyu Media      windows;linux             0   
4  The Quantum Astrophysicists Guild  windows;mac;linux             0   

                                          categories  \
0           Single-player;Partial Controller Support   
1           Single-player;Partial Controller Support   
2  Single-player;Local Co-op;Shared/Split Screen;...   
3  Single-player;Steam Achievements;Steam Trading...   
4  Single-player;Steam Achievements;Full controll...   

                         genres              steamspy_tags  achievements  \
0                  Action;Indie         Action;Indie;Space             0   
1                        Casual            Casual;VR;Anime             0   
2     Violent;Gore;Action;Indie  Action;Metroidvania;Indie            60   
3                  Action;Indie  Action;Indie;Shoot 'Em Up            53   
4  Action;Casual;Indie;Strategy        Indie;Action;Casual            24   

   positive_ratings  negative_ratings  average_playtime  median_playtime  \
0                 2                 2                 0                0   
1                30                 4                 0                0   
2               271                30               279              279   
3                16                 0                 0                0   
4                29                 1                 0                0   

        owners  price  
0      0-20000   2.89  
1      0-20000   3.99  
2  20000-50000  10.29  
3      0-20000   4.79  
4      0-20000   7.19

In [425]:
df_train.shape

(25044, 18)

## Label Encoding

In [426]:
le = LabelEncoder()

df_train['name'] = le.fit_transform(df_train['name'])
df_train['release_date'] = le.fit_transform(df_train['release_date'])
df_train['developer'] = le.fit_transform(df_train['developer'])
df_train['publisher'] = le.fit_transform(df_train['publisher'])
df_train['platforms'] = le.fit_transform(df_train['platforms'])
df_train['categories'] = le.fit_transform(df_train['categories'])
df_train['genres'] = le.fit_transform(df_train['genres'])
df_train['steamspy_tags'] = le.fit_transform(df_train['steamspy_tags'])
df_train['owners'] = le.fit_transform(df_train['owners'])

In [427]:
df_train.head()

appid   name  release_date  english  developer  publisher  platforms  \
0  708830  20450          2001        1       3921       3287          3   
1  538000   9891          1911        1       7281       2889          3   
2  603530    351          1980        1       8318       6955          6   
3  564040  24229          1789        1        333       7885          4   
4  951940   1015          2506        1       1881      11136          6   

   required_age  categories  genres  steamspy_tags  achievements  \
0             0        2591     388            356             0   
1             0        2591     683           1747             0   
2             0         799    1442            409            60   
3             0        2932     388            350            53   
4             0        2772     307           2986            24   

   positive_ratings  negative_ratings  average_playtime  median_playtime  \
0                 2                 2                 0                0   
1                30                 4                 0                0   
2               271                30               279              279   
3                16                 0                 0                0   
4                29                 1                 0                0   

   owners  price  
0       0   2.89  
1       0   3.99  
2       5  10.29  
3       0   4.79  
4       0   7.19

In [428]:
df_test['name'] = le.fit_transform(df_test['name'])
df_test['release_date'] = le.fit_transform(df_test['release_date'])
df_test['developer'] = le.fit_transform(df_test['developer'])
df_test['publisher'] = le.fit_transform(df_test['publisher'])
df_test['platforms'] = le.fit_transform(df_test['platforms'])
df_test['categories'] = le.fit_transform(df_test['categories'])
df_test['genres'] = le.fit_transform(df_test['genres'])
df_test['steamspy_tags'] = le.fit_transform(df_test['steamspy_tags'])
df_test['owners'] = le.fit_transform(df_test['owners'])

In [429]:
df_test.head()

appid  name  release_date  english  developer  publisher  platforms  \
0   514520  1540           440        1        896        485          0   
1  1012710   577          1074        1       1312       1173          0   
2   279260  1353           145        1       1135       1005          0   
3   220090  1699            80        1       1408       1259          3   
4   788870   843           884        1       1761       1569          0   

   required_age  categories  genres  steamspy_tags  achievements  \
0             0          82     279            631            14   
1             0         193      89            362             0   
2             0         514     174            193            21   
3             0         539     174            215             0   
4             0         414      53            423             0   

   positive_ratings  negative_ratings  average_playtime  median_playtime  \
0                 6                 3                 0                0   
1                 0                 1                88               88   
2               264                99               332              332   
3               902               129               303              327   
4                 6                11                 0                0   

   owners  price  
0       0   0.99  
1       0   7.19  
2       7   4.79  
3       5   5.99  
4       0   7.19

## Data Preparation

In [430]:
df_train.shape

(25044, 18)

In [431]:
df_train = df_train.drop(['platforms','required_age','english'],axis=1)

In [432]:
df_train.shape

(25044, 15)

In [433]:
x_train = df_train.iloc[:,0:15].values
y_train = df_train.iloc[:,-1].values

In [434]:
x_train[0]

array([7.0883e+05, 2.0450e+04, 2.0010e+03, 3.9210e+03, 3.2870e+03,
       2.5910e+03, 3.8800e+02, 3.5600e+02, 0.0000e+00, 2.0000e+00,
       2.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.8900e+00])

In [435]:
df_test = df_test.drop(['platforms','required_age','english'],axis=1)

In [436]:
x_test = df_test.iloc[:,0:15].values
y_test = df_test.iloc[:,-1].values

In [437]:
x_test.shape

(2031, 15)

In [438]:
x_id = x_test[:,0]

In [439]:
from sklearn.preprocessing import StandardScaler

In [440]:
scaler = StandardScaler()

In [441]:
scaler.fit(x_train)
scaler.transform(x_train)
scaler.transform(x_test)
x_train.std(axis=0)

array([2.51416564e+05, 7.21968234e+03, 5.60011657e+02, 4.65297790e+03,
       3.93787319e+03, 1.04041050e+03, 3.62010836e+02, 1.74473756e+03,
       3.50991225e+02, 1.95622746e+04, 4.44773611e+03, 1.78300303e+03,
       2.11457302e+03, 3.01164148e+00, 7.28440662e+00])

In [442]:
## Normalisation
#x_mean = x_train.mean(axis=0)
#x_std = x_train.std(axis=0)

#Apply the transformation
#x_train = (x_train-x_mean)/x_std

#x_test = (x_test-x_mean)/x_std

In [443]:
x_train.std(axis=0)

array([2.51416564e+05, 7.21968234e+03, 5.60011657e+02, 4.65297790e+03,
       3.93787319e+03, 1.04041050e+03, 3.62010836e+02, 1.74473756e+03,
       3.50991225e+02, 1.95622746e+04, 4.44773611e+03, 1.78300303e+03,
       2.11457302e+03, 3.01164148e+00, 7.28440662e+00])

## Linear Regression

In [444]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
#from sklearn.tree import DecisionTreeRegressor
#from sklearn import ensemble
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.ensemble import GradientBoostingRegressor
#from sklearn.neighbors import KNeighborsRegressor
#from sklearn.linear_model import ElasticNet
#from sklearn.linear_model import Lasso

In [445]:
model = LinearRegression()
#dtree = DecisionTreeRegressor()
#rfr = RandomForestRegressor()
#boost = GradientBoostingRegressor()

In [446]:
#reg = ensemble.GradientBoostingRegressor(**params)
#reg.fit(x_train, y_train)

In [452]:
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [454]:
y_model = model.predict(x_test)

In [455]:
model.score(x_train,y_train)

1.0

In [456]:
np.sqrt(mean_squared_error(y_model,y_test))

5.2144305463177567e-14

## Conversion Final

In [457]:
df_ = pd.DataFrame({'appid':x_id,'price':y_model})
df_ = df_.astype({'appid':int})
df_.to_csv('submission_Game.csv',index=False)